# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: API workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.14.2
      uses: actions/setup-node@v3
      with:
        node-version: "18.14.2"

    - name: Clean install deps
      run: npm ci
      
    - name: Build project
      run: npm run build

    - name: Create test coverage
    - run: npm run test:cov

    # - name: Upload testing reports
    #   run: |
    #     bash <(curl -s https://codecov.io/bash)
    #   env:
    #     CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3    
